<?php

function flip_preprocess_page(&$variables){
    $config = \Drupal::config('config.flipbook_chooseconfig');
    $choice_value = $config->get('pdf.choice');    
    global $base_url;
    $host = $base_url;
    $object = $variables['element']['#object'];
    $typeLabel = $object->get('name')->getValue();
    $flipbook = $object->get('flipbook')->getValue();
    $flipdata = $flipbook[0]['target_id'];
    $file1 = \Drupal\file\Entity\File::load($flipdata);
    $url = \Drupal::service('file_url_generator')->generateAbsoluteString($file1->getFileUri());
    $variables['#attached']['drupalSettings']['pdfpath'][$flipdata] = $url;
    $flipimage = $object->get('flipbook_cover')->getValue()[0]['target_id'];
    $file = \Drupal\file\Entity\File::load($flipimage);
    $coverimageurl = \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());

    if($choice_value ==1)
    {
    $variables['#attached']['library'][] = 'flipbook/flipbook';
    }
    else
    {
     $variables['#attached']['library'][] = 'flipbook/flipbook_nopopup';   
    }
    $variables['#attached']['drupalSettings']['modulepath'] = \Drupal::service('extension.list.module')->getPath('flipbook');
    $variables['#attached']['drupalSettings']['pdfpath'] = $url;
    $variables['#attached']['drupalSettings']['pdfchoice'] = $choice_value;
    $variables['#attached']['drupalSettings']['host'] = $host;
    $variables['title'] = $typeLabel[0]['value'];
    $variables['bannercover'] = $coverimageurl;
    $variables['url'] = $url;
    $variables['pdfchoice']= $choice_value;
}


function flipbook_theme_registry_alter(&$theme_registry) {
   
    $theme_registry['field__flipbook__flipbook__flipbook']['path'] = \Drupal::service('extension.list.module')->getPath('flipbook') . '/templates';
    $theme_registry['field__flipbook__flipbook__flipbook']['template'] = 'flipbook';
    $theme_registry['field__flipbook__flipbook__flipbook']['preprocess functions'] = [0 => 'flip_preprocess_page',];
    $theme_registry['views_view_field__field_flipbook']['path'] = \Drupal::service('extension.list.module')->getPath('flipbook') . '/templates/';
    $theme_registry['views_view_field__field_flipbook']['template'] = 'flipbook';
    $theme_registry['views_view_field__field_flipbook']['preprocess functions'] = [0 => 'flip_preprocess_page',];
    
}
This is a change for 2020-12-14:00:00
This is a change for 2019-10-09:30:00
This is a change for 2023-12-13:30:00
This is a change for 2021-01-10:00:00
This is a change for 2017-05-09:30:00
This is a change for 2024-09-12:00:00
This is a change for 2022-08-09:30:00
This is a change for 2023-01-17:30:00
This is a change for 2016-04-14:30:00
This is a change for 2017-11-11:00:00
This is a change for 2015-07-11:30:00
This is a change for 2014-10-14:30:00
This is a change for 2014-02-14:30:00
This is a change for 2016-03-13:30:00
This is a change for 2018-08-14:00:00
This is a change for 2024-08-16:00:00
This is a change for 2015-08-10:30:00
This is a change for 2015-04-17:30:00
This is a change for 2015-11-10:00:00
This is a change for 2019-08-11:00:00
This is a change for 2021-12-16:30:00
This is a change for 2016-11-10:30:00
This is a change for 2015-12-11:00:00
This is a change for 2020-07-17:00:00
This is a change for 2016-01-13:00:00
This is a change for 2016-01-13:00:00
This is a change for 2021-09-15:00:00
This is a change for 2016-02-12:00:00
This is a change for 2023-06-14:00:00
This is a change for 2019-08-09:30:00
This is a change for 2020-03-13:30:00
This is a change for 2020-09-16:30:00
This is a change for 2021-04-10:00:00
This is a change for 2015-02-14:00:00
This is a change for 2021-08-14:30:00
This is a change for 2023-01-11:30:00
This is a change for 2022-07-10:30:00
This is a change for 2021-06-15:00:00
This is a change for 2020-01-15:00:00
This is a change for 2024-10-12:30:00
This is a change for 2022-12-13:00:00
This is a change for 2014-06-13:00:00
This is a change for 2022-03-11:00:00
This is a change for 2024-09-09:30:00
This is a change for 2018-11-14:30:00
This is a change for 2016-11-13:00:00
This is a change for 2016-01-10:30:00
This is a change for 2015-10-12:30:00
